CREATE TABLE [acsa].[SWIFT_SKU_INTERCOMPANY] (
    [SKU_INTERCOMPAY] INT          IDENTITY (1, 1) NOT NULL,
    [MASTER_ID]       VARCHAR (50) NOT NULL,
    [ITEM_CODE]       VARCHAR (50) NOT NULL,
    [SOURCE]          VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([SKU_INTERCOMPAY] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_SWIFT_SKU_INTERCOMPANY_MASTER_ID_SOURCE]
    ON [acsa].[SWIFT_SKU_INTERCOMPANY]([MASTER_ID] ASC, [SOURCE] ASC)
    INCLUDE([ITEM_CODE]);

