CREATE TABLE [acsa].[SWIFT_POLYGON_POINT] (
    [POLYGON_ID] INT           NOT NULL,
    [POSITION]   INT           NOT NULL,
    [LATITUDE]   VARCHAR (250) NOT NULL,
    [LONGITUDE]  VARCHAR (250) NOT NULL,
    PRIMARY KEY CLUSTERED ([POLYGON_ID] ASC, [POSITION] ASC),
    FOREIGN KEY ([POLYGON_ID]) REFERENCES [acsa].[SWIFT_POLYGON] ([POLYGON_ID])
);

