


GO
CREATE NONCLUSTERED INDEX [IDX_TEMPORAL]
    ON [dbo].[SOD_TEMPORAL]([POS_TERMINAL] ASC, [AUTHORIZED] ASC, [IS_READY_TO_SEND] ASC, [POSTED_DATETIME] ASC)
    INCLUDE([SALES_ORDER_ID], [CLIENT_ID], [GPS_URL], [TOTAL_AMOUNT], [POSTED_BY], [IMAGE_1], [IMAGE_2], [DELIVERY_DATE], [IS_POSTED_ERP], [POSTED_RESPONSE], [IS_PARENT], [REFERENCE_ID], [WAREHOUSE], [DOC_SERIE], [DOC_NUM], [IS_VOID], [SALES_ORDER_TYPE], [DISCOUNT], [IS_DRAFT], [ASSIGNED_BY]);

