CREATE PROCEDURE [acsa].[SWIFT_SP_DELETECLASSIFICATION]
@CLASSIFICATION INT,
@pResult varchar(250) OUTPUT
AS

DECLARE @NAME_CLASSIFICATION VARCHAR(50)
DECLARE @VALUE_TEXT VARCHAR(50)
DECLARE @MPC01 VARCHAR(50)
SET @NAME_CLASSIFICATION = (SELECT NAME_CLASSIFICATION FROM [acsa].SWIFT_CLASSIFICATION WHERE CLASSIFICATION = @CLASSIFICATION)
SET @VALUE_TEXT = (SELECT VALUE_TEXT_CLASSIFICATION FROM [acsa].SWIFT_CLASSIFICATION WHERE CLASSIFICATION = @CLASSIFICATION)
SET @MPC01 = (SELECT MPC01 FROM [acsa].SWIFT_CLASSIFICATION WHERE CLASSIFICATION = @CLASSIFICATION)
IF ((SELECT COUNT(A.WEATHER_WAREHOUSE) FROM [acsa].SWIFT_WAREHOUSES AS A WHERE A.WEATHER_WAREHOUSE =  @VALUE_TEXT )
+ (SELECT COUNT(B.CLASSIFICATION_LOCATION) FROM [acsa].SWIFT_LOCATIONS AS B WHERE B.CLASSIFICATION_LOCATION = @VALUE_TEXT  )
+ (SELECT COUNT(C.CLASSIFICATION_SKU) FROM [acsa].SWIFT_SKU AS C WHERE C.CLASSIFICATION_SKU = @VALUE_TEXT  )
+ (SELECT COUNT(D.CLASSIFICATION_CUSTOMER) FROM [acsa].SWIFT_CUSTOMERS AS D WHERE D.CLASSIFICATION_CUSTOMER = @VALUE_TEXT  )
+ (SELECT COUNT(E.CLASSIFICATION_PROVIDER) FROM [acsa].SWIFT_PROVIDERS AS E WHERE E.CLASSIFICATION_PROVIDER = @VALUE_TEXT  )
+ (SELECT COUNT(F.CLASSIFICATION_VEHICLE) FROM [acsa].SWIFT_VEHICLES AS F WHERE F.CLASSIFICATION_VEHICLE = @VALUE_TEXT  )
+ (SELECT COUNT(G.TYPE_RECEPTION) FROM [acsa].SWIFT_RECEPTION_HEADER AS G WHERE G.TYPE_RECEPTION = @MPC01  )
+ (SELECT COUNT(H.CLASSIFICATION_PICKING) FROM [acsa].SWIFT_PICKING_HEADER AS H WHERE H.CLASSIFICATION_PICKING = @VALUE_TEXT  )
+ (SELECT COUNT(I.[USER_TYPE]) FROM [acsa].USERS AS I WHERE I.[USER_TYPE] = @VALUE_TEXT )
) = 0
BEGIN 
	DELETE FROM SWIFT_CLASSIFICATION WHERE CLASSIFICATION=@CLASSIFICATION
	--SELECT @pResult = ''
END
ELSE
	BEGIN
		SELECT @pResult = 'El dato no se puede eliminar debido a que está siendo utilizado'
	END



