


-- =============================================
-- Autor:				ppablo.loukota
-- Fecha de Creacion: 	16-12-2015
-- Description:			Vista que obtiene detalles de bodegas 

-- Modificacion 3/14/2017 @ A-Team Sprint Ebonne
-- diego.as
-- Se modifica para que apunte a la BD SAP_INTERCOMPANY

-- Modificacion 4/21/2017 @ A-Team Sprint Hondo
-- rodrigo.gomez
-- Se agregaron las referencias de MasterId, Onwer y OwnerId
/*
-- Ejemplo de Ejecucion:
				SELECT * FROM [DIPROCOM].[ERP_VIEW_WAREHOUSE]
*/
-- =============================================

CREATE VIEW [DIPROCOM].[ERP_VIEW_WAREHOUSE]
AS
SELECT
  CODE_WAREHOUSE COLLATE DATABASE_DEFAULT AS CODE_WAREHOUSE
 ,[DESCRIPTION] COLLATE DATABASE_DEFAULT AS [DESCRIPTION]
 ,[WEATHER_WAREHOUSE] COLLATE DATABASE_DEFAULT AS [WEATHER_WAREHOUSE]
 ,[STATUS_WAREHOUSE] COLLATE DATABASE_DEFAULT AS [STATUS_WAREHOUSE]
 ,GETDATE() AS [LAST_UPDATE]
 ,[LAST_UPDATE_BY] COLLATE DATABASE_DEFAULT AS [LAST_UPDATE_BY]
 ,[IS_EXTERNAL] AS [IS_EXTERNAL]
 ,[OWNER] COLLATE DATABASE_DEFAULT AS [OWNER]
 ,[OWNER_ID] COLLATE DATABASE_DEFAULT AS [OWNER_ID]
FROM OPENQUERY(DIPROCOM_SERVER, '
SELECT  
	RTRIM(CODIGO_BODEGA)  AS [CODE_WAREHOUSE]  
	,RTRIM(DESCRIPCION_BODEGA)  AS [DESCRIPTION]  
	,''40''      AS [WEATHER_WAREHOUSE]
	,''ACTIVA''   AS [STATUS_WAREHOUSE]
	,GETDATE()  AS [LAST_UPDATE]  
	,''BULKDATA'' AS [LAST_UPDATE_BY]
	,NULL	   AS [IS_EXTERNAL]	
	,''Diprocom'' AS OWNER
	,CONVERT(VARCHAR(50),CODIGO_BODEGA) COLLATE SQL_Latin1_General_CP1_CI_AS AS OWNER_ID
FROM [SONDA].[dbo].[vsMAESTRO_DE_BODEGAS] 
ORDER BY [CODE_WAREHOUSE]
')