
CREATE view [DIPROCOM].[SONDA_VIEW_VOID_REASONS]
as
select 
NAME_CLASSIFICATION REASON_ID,
VALUE_TEXT_CLASSIFICATION REASON_DESCRIPTION
  from  [DIPROCOM].SWIFT_CLASSIFICATION
WHERE 
	GROUP_CLASSIFICATION ='VOID_REASONS' 




