CREATE VIEW [PACASA].[SWIFT_VIEW_WAREHOUSES_NOT_SELLER]
AS
SELECT *
FROM [PACASA].[SWIFT_VIEW_WAREHOUSES] VW
WHERE NOT EXISTS(SELECT 1
				FROM [PACASA].[SWIFT_VIEW_SELLER_LOGIN] SL
				WHERE VW.CODE_WAREHOUSE = SL.DEFAULT_WAREHOUSE)




