CREATE VIEW [DIPROCOM].[SWIFT_VIEW_WAREHOUSES_NOT_SELLER]
AS
SELECT *
FROM [DIPROCOM].[SWIFT_VIEW_WAREHOUSES] VW
WHERE NOT EXISTS(SELECT 1
				FROM [DIPROCOM].[SWIFT_VIEW_SELLER_LOGIN] SL
				WHERE VW.CODE_WAREHOUSE = SL.DEFAULT_WAREHOUSE AND [SL].[DEFAULT_WAREHOUSE]<>'04')




