CREATE VIEW [acsa].[SWIFT_VIEW_SAP_PICKING] 
AS
SELECT 
   SAP_PICKING_ID 			 AS SAP_PICKING_ID,
    ERP_DOC				AS ERP_DOC,
	CUSTOMER_ID			AS CUSTOMER_ID,
	CUSTOMER_NAME		AS CUSTOMER_NAME,
 	SKU 					AS SKU ,
	SKU_DESCRIPTION  		AS SKU_DESCRIPTION,
	 QTY					AS QTY 
FROM
	SWIFT_INTERFACES_ONLINE.[acsa].ERP_VIEW_PICKING
