CREATE TABLE [DIPROCOM].[SWIFT_POLYGON_BY_ROUTE_082021] (
    [ROUTE]           INT NOT NULL,
    [POLYGON_ID]      INT NOT NULL,
    [ID_FREQUENCY]    INT NULL,
    [IS_MULTIPOLYGON] INT NOT NULL,
    [IS_MULTISELLER]  INT NOT NULL
);

