CREATE TABLE [SONDA].[SWIFT_TASKS_BK] (
    [TASK_ID]                INT           NOT NULL,
    [TASK_TYPE]              VARCHAR (15)  NULL,
    [TASK_DATE]              DATE          NULL,
    [SCHEDULE_FOR]           DATE          NULL,
    [CREATED_STAMP]          DATETIME      NULL,
    [ASSIGEND_TO]            VARCHAR (25)  NULL,
    [ASSIGNED_BY]            VARCHAR (25)  NULL,
    [ASSIGNED_STAMP]         DATETIME      NULL,
    [CANCELED_STAMP]         DATETIME      NULL,
    [CANCELED_BY]            VARCHAR (25)  NULL,
    [ACCEPTED_STAMP]         DATETIME      NULL,
    [COMPLETED_STAMP]        DATETIME      NULL,
    [RELATED_PROVIDER_CODE]  VARCHAR (25)  NULL,
    [RELATED_PROVIDER_NAME]  VARCHAR (250) NULL,
    [EXPECTED_GPS]           VARCHAR (100) NULL,
    [POSTED_GPS]             VARCHAR (100) NULL,
    [TASK_STATUS]            VARCHAR (10)  NULL,
    [TASK_COMMENTS]          VARCHAR (150) NULL,
    [TASK_SEQ]               INT           NULL,
    [REFERENCE]              VARCHAR (150) NULL,
    [SAP_REFERENCE]          VARCHAR (150) NULL,
    [COSTUMER_CODE]          VARCHAR (25)  NULL,
    [COSTUMER_NAME]          VARCHAR (250) NULL,
    [RECEPTION_NUMBER]       INT           NULL,
    [PICKING_NUMBER]         INT           NULL,
    [COUNT_ID]               VARCHAR (50)  NULL,
    [ACTION]                 VARCHAR (50)  NULL,
    [SCANNING_STATUS]        VARCHAR (50)  NULL,
    [ALLOW_STORAGE_ON_DIFF]  INT           NULL,
    [CUSTOMER_PHONE]         VARCHAR (50)  NULL,
    [TASK_ADDRESS]           VARCHAR (250) NULL,
    [VISIT_HOUR]             DATETIME      NULL,
    [ROUTE_IS_COMPLETED]     INT           NULL,
    [EMAIL_TO_CONFIRM]       VARCHAR (150) NULL,
    [DISTANCE_IN_KMS]        FLOAT (53)    NULL,
    [DOC_RESOLUTION]         VARCHAR (50)  NULL,
    [DOC_SERIE]              VARCHAR (100) NULL,
    [DOC_NUM]                INT           NULL,
    [COMPLETED_SUCCESSFULLY] NUMERIC (18)  NULL,
    [REASON]                 VARCHAR (250) NULL,
    [TASK_ID_HH]             INT           NULL,
    [IN_PLAN_ROUTE]          INT           NULL,
    [CREATE_BY]              VARCHAR (250) NULL
);

