CREATE TABLE [DIPROCOM].[SWIFT_VEHICLE_X_USER] (
    [VEHICLE] INT          IDENTITY (1, 1) NOT NULL,
    [LOGIN]   VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_VEHICLE_X_USER] PRIMARY KEY CLUSTERED ([VEHICLE] ASC, [LOGIN] ASC),
    CONSTRAINT [FK_VEHICLE_X_USER_VEHICLE] FOREIGN KEY ([VEHICLE]) REFERENCES [DIPROCOM].[SWIFT_VEHICLES] ([VEHICLE])
);



