CREATE TABLE [DIPROCOM].[SWIFT_FREQUENCY_X_CUSTOMER_24082021] (
    [ID_FREQUENCY]      INT          NOT NULL,
    [CODE_CUSTOMER]     VARCHAR (50) NOT NULL,
    [PRIORITY]          INT          NULL,
    [LAST_WEEK_VISITED] DATE         NULL
);

