CREATE TABLE [PACASA].[SWIFT_PROMO_SKU_SALES_BY_MULTIPLE] (
    [PROMO_ID]                             INT          NOT NULL,
    [CODE_SKU]                             VARCHAR (50) NOT NULL,
    [PACK_UNIT]                            INT          NOT NULL,
    [MULTIPLE]                             INT          DEFAULT ((1)) NOT NULL,
    [SWIFT_PROMO_SKU_SALES_BY_MULTIPLE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [LAST_UPDATE]                          DATETIME     DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC),
    FOREIGN KEY ([PACK_UNIT]) REFERENCES [PACASA].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [PACASA].[SWIFT_PROMO] ([PROMO_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PROMO_SKU_SALES_BY_MULTIPLE_ID]
    ON [PACASA].[SWIFT_PROMO_SKU_SALES_BY_MULTIPLE]([SWIFT_PROMO_SKU_SALES_BY_MULTIPLE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_SKU_SALES_BY_MULTIPLE_LAST_UPDATE]
    ON [PACASA].[SWIFT_PROMO_SKU_SALES_BY_MULTIPLE]([LAST_UPDATE] ASC);

