CREATE TABLE [acsa].[SWIFT_PROMO_DISCOUNT_BY_SCALE] (
    [PROMO_DISCOUNT_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]          INT             NOT NULL,
    [CODE_SKU]          VARCHAR (50)    NOT NULL,
    [PACK_UNIT]         INT             NOT NULL,
    [LOW_LIMIT]         INT             NOT NULL,
    [HIGH_LIMIT]        INT             NOT NULL,
    [DISCOUNT]          NUMERIC (18, 6) NOT NULL,
    [DISCOUNT_TYPE]     VARCHAR (50)    DEFAULT ('PERCENTAGE') NOT NULL,
    [LAST_UPDATE]       DATETIME        DEFAULT (getdate()) NOT NULL,
    [IS_UNIQUE]         INT             DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_DISCOUNT_ID] ASC),
    FOREIGN KEY ([PACK_UNIT]) REFERENCES [acsa].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    FOREIGN KEY ([PROMO_ID]) REFERENCES [acsa].[SWIFT_PROMO] ([PROMO_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_SWIFT_PROMO_DISCOUNT_BY_SCALE_T0]
    ON [acsa].[SWIFT_PROMO_DISCOUNT_BY_SCALE]([CODE_SKU] ASC, [PACK_UNIT] ASC, [PROMO_ID] ASC)
    INCLUDE([HIGH_LIMIT], [LOW_LIMIT], [PROMO_DISCOUNT_ID], [DISCOUNT], [DISCOUNT_TYPE]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_DISCOUNT_BY_SCALE_LAST_UPDATE]
    ON [acsa].[SWIFT_PROMO_DISCOUNT_BY_SCALE]([LAST_UPDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_DISCOUNT_BY_SCALE_PROMO_ID]
    ON [acsa].[SWIFT_PROMO_DISCOUNT_BY_SCALE]([PROMO_ID] ASC)
    INCLUDE([CODE_SKU], [PACK_UNIT], [LOW_LIMIT], [HIGH_LIMIT], [DISCOUNT], [DISCOUNT_TYPE]);

