CREATE TABLE [DIPROCOM].[SWIFT_POLYGON_POINT_082021] (
    [POLYGON_ID] INT           NOT NULL,
    [POSITION]   INT           NOT NULL,
    [LATITUDE]   VARCHAR (250) NOT NULL,
    [LONGITUDE]  VARCHAR (250) NOT NULL
);

