CREATE TABLE [DIPROCOM].[SWIFT_CUSTOMER_ASSOCIATE_TO_POLYGON_082021] (
    [ASSOCIATE_ID]  INT           IDENTITY (1, 1) NOT NULL,
    [POLYGON_ID]    INT           NULL,
    [POLYGON_NAME]  VARCHAR (250) NULL,
    [POLYGON_TYPE]  VARCHAR (250) NULL,
    [CODE_CUSTOMER] VARCHAR (50)  NULL,
    [GPS_CUSTOMER]  VARCHAR (MAX) NULL,
    [LAST_UPDATE]   DATETIME      NULL
);

