CREATE TABLE [SONDA].[SWIFT_POLYGON_POINT_BK] (
    [POLYGON_ID] INT           NOT NULL,
    [POSITION]   INT           NOT NULL,
    [LATITUDE]   VARCHAR (250) NOT NULL,
    [LONGITUDE]  VARCHAR (250) NOT NULL
);

