CREATE TABLE [acsa].[SWIFT_PRICE_LIST_BK] (
    [CODE_PRICE_LIST] VARCHAR (25)  NOT NULL,
    [NAME_PRICE_LIST] VARCHAR (50)  NULL,
    [COMMENT]         VARCHAR (250) NULL,
    [LAST_UPDATE]     DATE          NULL,
    [LAST_UPDATE_BY]  VARCHAR (50)  NULL
);

