-- ======================================================
-- Autor:				        diego.as
-- Fecha de Creacion: 	10-01-2017 @ A-TEAM Sprint Balder
-- Description:			SP que obtiene las bodegas de 3PL
/*
  Ejemplo de Ejecucion:
  --
    EXEC [SONDA].SWIFT_SP_GET_3PL_WAREHOUSE
      @CODE_WAREHOUSE = 'BOD.503'
*/

-- ======================================================
CREATE PROCEDURE [SONDA].[SWIFT_SP_GET_3PL_WAREHOUSE]
(
  @CODE_WAREHOUSE VARCHAR(50) = NULL
  )
  AS
BEGIN
  SELECT 
 W.[CODE_WAREHOUSE]
 ,W.CODE_WAREHOUSE [WAREHOUSE_ID] --codigo bodega 
 ,W.DESCRIPTION_WAREHOUSE [NAME]
 ,'' [COMMENTS]
 ,W.ERP_WAREHOUSE [ERP_WAREHOUSE]
 ,0 [ALLOW_PICKING]
 ,0 [DEFAULT_RECEPTION_LOCATION]
 ,W.DESCRIPTION_WAREHOUSE [SHUNT_NAME]
 ,W.WEATHER_WAREHOUSE [WAREHOUSE_WEATHER]
 ,0 [WAREHOUSE_STATUS]
 ,0 [IS_3PL_WAREHUESE]
 ,W.ADDRESS_WAREHOUSE [WAHREHOUSE_ADDRESS]
 ,W.GPS_WAREHOUSE [GPS_URL]
 ,WXD.DISTRIBUTION_CENTER_ID [DISTRIBUTION_CENTER_ID]
 FROM [SONDA].[SWIFT_WAREHOUSES] [W]
	INNER JOIN [SONDA].[SWIFT_WAREHOUSE_X_DISTRIBUTION_CENTER] WXD
			ON (W.CODE_WAREHOUSE = WXD.CODE_WAREHOUSE)
  WHERE (W.[CODE_WAREHOUSE] = @CODE_WAREHOUSE OR W.[CODE_WAREHOUSE] IS NULL)
  END