
CREATE FUNCTION [DIPROCOM].[SWIFT_FUNC_GET_MANIFEST_DETAIL]
(	
	@MANIFEST_HEADER INT
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT DISTINCT
		A.MANIFEST_HEADER
		,B.CODE_CUSTOMER
		,B.CODE_PICKING AS 'NUMERO_PICKING'
		,B.REFERENCE
		,B.DOC_SAP_PICKING
		,C.NAME_CUSTOMER
  ,CASE 
				WHEN B.[TYPE] = 'PICKING'
          THEN ISNULL(C.ADRESS_CUSTOMER,'N/A')
        WHEN B.[TYPE] = 'INVOICE'
          THEN ISNULL(ISNULL(G.Address,G.Address2), C.ADRESS_CUSTOMER) COLLATE DATABASE_DEFAULT
  END AS ADRESS_CUSTOMER
		,ISNULL(C.PHONE_CUSTOMER,'N/A') AS PHONE_CUSTOMER
		,CASE 
				WHEN B.[TYPE] = 'PICKING'
				   THEN D.SCHEDULE_FOR
				WHEN B.[TYPE] = 'INVOICE'
				THEN G.DocDate
		END  AS 'FECHA_PROPUESTA'
		,CASE 
				WHEN B.[TYPE] = 'PICKING'
				   THEN ISNULL(D.COMMENTS,'NINGUNA OBSERVACION')
				WHEN B.[TYPE] = 'INVOICE'
				THEN  ISNULL(G.Comments,'NINGUNA OBSERVACION') COLLATE DATABASE_DEFAULT
		END  AS 'OBSERVACIONES'
		,CASE 
				WHEN B.[TYPE] = 'PICKING'
					THEN COUNT(E.CODE_SKU)
				WHEN B.[TYPE] = 'INVOICE'
					THEN SUM(H.Quantity)
		END  AS 'CANTIDAD'
		,CASE 
				WHEN B.[TYPE] = 'PICKING'
					THEN ISNULL((SELECT TOP 1 SELLER_NAME FROM OPENQUERY (ERPSERVER,'SELECT SE.SlpName as SELLER_NAME, PO.DocNum AS ERP_DOC
	FROM         [BD_Prueba_Viscosa].dbo.RDR1 AS POD INNER JOIN
						  [BD_Prueba_Viscosa].dbo.ORDR AS PO ON PO.DocEntry = POD.DocEntry
						  INNER JOIN
						[BD_Prueba_Viscosa].dbo.OSLP AS SE
						ON SE.SlpCode =  PO.SlpCode
	WHERE  po.DocStatus=''O'' AND pod.LineStatus=''O'' AND (PO.DocType = ''I'') ') WHERE ERP_DOC = B.DOC_SAP_PICKING),'N/A')
				WHEN B.[TYPE] = 'INVOICE'
					THEN (SELECT SlpName COLLATE DATABASE_DEFAULT FROM OPENQUERY(ERPSERVER,'SELECT SlpName , SlpCode
						  FROM [BD_Prueba_Viscosa].dbo.OSLP') AS SE WHERE SE.SlpCode = G.SlpCode) 
		END  AS 'SELLER_NAME'
	FROM
		DIPROCOM.SWIFT_MANIFEST_HEADER AS A
	LEFT OUTER JOIN
		DIPROCOM.SWIFT_MANIFEST_DETAIL AS B
	ON A.MANIFEST_HEADER = B.CODE_MANIFEST_HEADER
	LEFT OUTER JOIN
		DIPROCOM.SWIFT_VIEW_ALL_COSTUMER AS C
	ON B.CODE_CUSTOMER = C.CODE_CUSTOMER
	LEFT OUTER JOIN
		DIPROCOM.SWIFT_PICKING_HEADER AS D
	ON B.CODE_PICKING = D.PICKING_HEADER
	LEFT OUTER JOIN
		DIPROCOM.SWIFT_PICKING_DETAIL AS E
	ON B.CODE_PICKING = E.PICKING_HEADER
	LEFT OUTER JOIN
		DIPROCOM.SWIFT_TXNS AS F
	ON E.CODE_SKU = F.TXN_CODE_SKU AND B.CODE_PICKING = F.HEADER_REFERENCE
	LEFT OUTER JOIN
		SWIFT_INTERFACES.DIPROCOM.ERP_VIEW_INVOICE_HEADER AS G
	ON G.DocEntry = B.CODE_PICKING
	LEFT OUTER JOIN
		SWIFT_INTERFACES.DIPROCOM.ERP_VIEW_INVOICE_DETAIL AS H
	ON G.DocEntry = H.DocEntry
	WHERE A.MANIFEST_HEADER = @MANIFEST_HEADER
	GROUP BY 
		A.MANIFEST_HEADER
		,B.CODE_PICKING
		,B.REFERENCE
		,B.DOC_SAP_PICKING
		,C.NAME_CUSTOMER
		,C.ADRESS_CUSTOMER
		,C.PHONE_CUSTOMER
		,D.SCHEDULE_FOR
		,D.COMMENTS
		,B.[TYPE]
		,G.DocDate
		,G.Comments
		,G.SlpCode
		,B.CODE_CUSTOMER
  ,G.Address,G.Address2
)




