CREATE FUNCTION [acsa].[SWIFT_FUNCTION_GET_SAP_RECEPTION]
(	
	@pERP_DOC varchar(25)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT * 
		FROM [acsa].SWIFT_VIEW_SAP_RECEPTION
		WHERE UPPER(ERP_DOC) = UPPER(@pERP_DOC)
)
