CREATE PROCEDURE [PACASA].[SWIFT_DELETE_TEMP]
@HEADER_NUMBER_TEMP INT
AS
EXEC [PACASA].SWIFT_INSERT_IN_TRANSAXION_AND_TASK
DELETE [PACASA].SWIFT_TEMP_RECEPTION_HEADER --WHERE RECEPTION_HEADER = @HEADER_NUMBER_TEMP
DELETE [PACASA].SWIFT_TEMP_RECEPTION_DETAIL --WHERE RECEPTION_HEADER = @HEADER_NUMBER_TEMP
 










