CREATE PROCEDURE [DIPROCOM].[SWIFT_SP_DELETE_ROUTE_USER]
@LOGIN VARCHAR(50)

AS
UPDATE DIPROCOM.USERS SET 	
	SELLER_ROUTE = ''
WHERE [LOGIN] = @LOGIN

UPDATE dbo.SWIFT_USER SET 
	SELLER_ROUTE = ''
WHERE [LOGIN] = @LOGIN

