-- Autor:				pedro.loukota
-- Fecha de Creacion: 	11-11-2015
-- Description:			Obtiene Bodegas no asignadas a clientes
/*
-- Ejemplo de Ejecucion:				
				select [PACASA].SWIFT_SP_GET_NOTASIGN_WAREHOUSES
*/
CREATE PROCEDURE [PACASA].SWIFT_SP_GET_NOTASIGN_WAREHOUSES

@LOGIN varchar(50)
AS
BEGIN

DECLARE @TOTALASSIGN INT 

SELECT @TOTALASSIGN =  COUNT(*) FROM [PACASA].[SWIFT_WAREHOUSES] 
	
			WHERE [PACASA].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE] NOT IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [PACASA].[USERS] WHERE [PACASA].[USERS].CORRELATIVE != @LOGIN OR [PACASA].[USERS].LOGIN = NULL)


IF @TOTALASSIGN > 0
 BEGIN

		    SELECT  * FROM [PACASA].[SWIFT_WAREHOUSES] 
	
			WHERE [PACASA].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE] NOT IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [PACASA].[USERS] WHERE [PACASA].[USERS].CORRELATIVE != @LOGIN OR [PACASA].[USERS].LOGIN = NULL)

		UNION	
			SELECT  * FROM [PACASA].[SWIFT_WAREHOUSES] 
	
			WHERE [PACASA].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE]  IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [PACASA].[USERS] WHERE [PACASA].[USERS].CORRELATIVE = @LOGIN)
			
		ORDER BY [PACASA].[SWIFT_WAREHOUSES].[DESCRIPTION_WAREHOUSE]			
			
END


IF @TOTALASSIGN = 0
 BEGIN

		    SELECT  * FROM [PACASA].[SWIFT_WAREHOUSES] 
	
END


END
