CREATE PROCEDURE [PACASA].[SWIFT_SP_DELETE_ROUTE_USER]
@LOGIN VARCHAR(50)

AS
UPDATE [PACASA].USERS SET 	
	SELLER_ROUTE = ''
WHERE [LOGIN] = @LOGIN

UPDATE dbo.SWIFT_USER SET 
	SELLER_ROUTE = ''
WHERE [LOGIN] = @LOGIN

