-- =============================================
-- Autor:					alberto.ruiz
-- Fecha de Creacion: 		04-07-2016
-- Description:			    Consulta para los vendedores en ruta

-- Modificacion:					hector.gonzalez
-- Fecha de Creacion: 		07-10-2016 sprint 2 TEAM-A
-- Description:			      Se agrego columna DELAY_TIME


/*
-- Ejemplo de Ejecucion:
        EXEC [DIPROCOM].[SWIFT_SP_GET_GPS_ACTIVE_ROUTE]
			@ASSIGNED_TO = '1046'
			,@START_DATE = '20161005'
			,@END_DATE = '20161008' 
*/
-- =============================================
CREATE PROCEDURE [DIPROCOM].SWIFT_SP_GET_GPS_ACTIVE_ROUTE_BK (
	@ASSIGNED_TO VARCHAR(50)
	,@START_DATE DATETIME
	,@END_DATE DATETIME
)
AS
BEGIN
	/*SELECT 
		A.ACCEPTED_STAMP,
		SUBSTRING(A.POSTED_GPS, 1, CHARINDEX(',', A.POSTED_GPS) - 1)  AS Latitude, 
		SUBSTRING(A.POSTED_GPS, CHARINDEX(',', A.POSTED_GPS) + 1, LEN(A.POSTED_GPS)) AS Longitude,
		A.ASSIGEND_TO AS ASSIGNED_TO,
		Replace(A.TASK_COMMENTS,CHAR(13),' ') AS TASK_COMMENTS ,
		A.COSTUMER_NAME AS CUSTOMER_NAME,
		Replace(A.TASK_ADDRESS,CHAR(13),' ') AS TASK_ADDRESS,
		A.COMPLETED_STAMP,
		ISNULL(B.TOTAL_AMOUNT,0) AS TOTAL_AMOUNT
	FROM [DIPROCOM].SWIFT_TASKS AS A
	LEFT OUTER JOIN
		[DIPROCOM].SWIFT_ORDERS AS B
		ON A.TASK_ID = B.TASK_SOURCE
	WHERE 
		A.POSTED_GPS IS NOT NULL 
		AND  ROUTE_IS_COMPLETED = '0'
		AND A.ASSIGEND_TO = @ASSIGNED_TO
		AND A.POSTED_GPS != '0,0'
		AND [A].[CREATED_STAMP] BETWEEN @STARDATE AND @ENDDATE
	UNION ALL*/
	SELECT
		ROW_NUMBER() OVER (ORDER BY [DH].[POSTED_DATETIME]) [LINE_NUMBER]
		,ISNULL([T].[ACCEPTED_STAMP],[DH].[POSTED_DATETIME]) [ACCEPTED_STAMP]
		,[DH].[Latitude] [LATITUDE]
		,[DH].[Longitude] [LONGITUDE]
		,[DH].[ASSIGNED_TO]
		,ISNULL([T].[TASK_COMMENTS],'Sin Comentario') [TASK_COMMENTS]
		,[DH].[CLIENT] [CODE_CUSTOMER]
		,[C].[NAME_CUSTOMER] [CUSTOMER_NAME]
		,ISNULL([C].[ADRESS_CUSTOMER],'') [TASK_ADDRESS]
		,ISNULL([T].[COMPLETED_STAMP],[DH].[POSTED_DATETIME]) [COMPLETED_STAMP]
		,[DH].[TOTAL_AMOUNT]
    ,T.COMPLETED_STAMP
    ,T.ACCEPTED_STAMP
    ,convert(varchar(3),DateDiff(s, T.ACCEPTED_STAMP , T.COMPLETED_STAMP)/3600)+':'+convert(varchar(3),DateDiff(s, T.ACCEPTED_STAMP , T.COMPLETED_STAMP)%3600/60)+':'+convert(varchar(3),(DateDiff(s, T.ACCEPTED_STAMP , T.COMPLETED_STAMP)%60)) AS DELAY_TIME
	FROM [DIPROCOM].[SWIFT_VIEW_DOCUMENTS_HEADER] [DH]
	INNER JOIN [DIPROCOM].[SWIFT_VIEW_ALL_COSTUMER] [C] ON (
		[DH].[CLIENT] = [C].[CODE_CUSTOMER]
	)
	LEFT JOIN [DIPROCOM].[SWIFT_TASKS] [T] ON (
		[DH].[TASK_ID] = [T].[TASK_ID]
	)
	WHERE [DH].ROUTE = @ASSIGNED_TO
		AND [DH].[STATUS] <> 5
		AND [DH].[POSTED_DATETIME] BETWEEN @START_DATE AND @END_DATE
		AND ([DH].[Latitude] != '0' OR [DH].[Longitude] != '0')
	ORDER BY
		[DH].[POSTED_DATETIME] ASC
END

