CREATE PROC [PACASA].[SWIFT_SP_GET_PORTFOLIO_SELLERS_AVAILABLE]
	@CODE_PORTFOLIO VARCHAR(50)
AS
	SELECT *
		, ISNULL((SELECT P.NAME_PORTFOLIO 
					FROM [PACASA].SWIFT_VIEW_PORTFOLIO_BY_SELLER PS1
							INNER JOIN [PACASA].SWIFT_VIEW_PORTFOLIO P ON PS1.CODE_PORTFOLIO = P.CODE_PORTFOLIO					
					WHERE S.SELLER_CODE = CODE_SELLER ), '') AS PORTFOLIO_ASSIGNED
	FROM [PACASA].SWIFT_VIEW_ALL_SELLERS S
	WHERE NOT EXISTS(SELECT 1
					FROM [PACASA].SWIFT_VIEW_PORTFOLIO_BY_SELLER PS
					WHERE S.SELLER_CODE = PS.CODE_SELLER
					AND PS.CODE_PORTFOLIO = @CODE_PORTFOLIO
	)







