

-- =============================================
-- Autor:				pablo.aguilar
-- Fecha de Creacion: 	18-08-2016
-- Description:			SP que importa las frecuencias a SWIFT_EXPRESS

/*
--DROP PROCEDURE [diprocom].[BULK_DATA_SP_IMPORT_ROUTE_FRECUENCY]
-- Ejemplo de Ejecucion:
				-- 
				EXEC [diprocom].[BULK_DATA_SP_IMPORT_ROUTE_FRECUENCY]
				SELECT * FROM SWIFT_EXPRESS.diprocom.SWIFT_FREQUENCY_X_CUSTOMER
				SELECT * FROM SWIFT_EXPRESS.diprocom.SWIFT_FREQUENCY
				SELECT * FROM SWIFT_EXPRESS.diprocom.SWIFT_TASKS
*/
-- =============================================
CREATE PROCEDURE [diprocom].[BULK_DATA_SP_IMPORT_ROUTE_FRECUENCY]
AS
BEGIN
  SET NOCOUNT ON;
  --
 

  TRUNCATE TABLE SWIFT_EXPRESS.diprocom.SWIFT_FREQUENCY_X_CUSTOMER 
  	
  DELETE FROM SWIFT_EXPRESS.diprocom.SWIFT_FREQUENCY 
	WHERE REFERENCE_SOURCE = 'BULK_DATA'

	INSERT INTO SWIFT_EXPRESS.diprocom.[SWIFT_FREQUENCY]
	        ( [CODE_FREQUENCY] ,
	          [SUNDAY] ,
	          [MONDAY] ,
	          [TUESDAY] ,
	          [WEDNESDAY] ,
	          [THURSDAY] ,
	          [FRIDAY] ,
	          [SATURDAY] ,
	          [FREQUENCY_WEEKS] ,
	          [LAST_WEEK_VISITED] ,
	          [LAST_UPDATED] ,
	          [LAST_UPDATED_BY] ,
	          [CODE_ROUTE] ,
	          [TYPE_TASK] ,
	          [REFERENCE_SOURCE] ,
	          [POLYGON_ID]
	        )
	SELECT 
		'SALE_' + SELLER_CODE+'_' + CONCAT(
		 CASE DATEPART(DW,GETDATE()) WHEN 2 THEN 1 ELSE 0 END 
		, CASE DATEPART(DW,GETDATE()) WHEN 3 THEN 1 ELSE 0 END 
		, CASE DATEPART(DW,GETDATE()) WHEN 4 THEN 1 ELSE 0 END 
		, CASE DATEPART(DW,GETDATE()) WHEN 5 THEN 1 ELSE 0 END 
		, CASE DATEPART(DW,GETDATE()) WHEN 6 THEN 1 ELSE 0 END 
		, CASE DATEPART(DW,GETDATE()) WHEN 7 THEN 1 ELSE 0 END 
		, CASE DATEPART(DW,GETDATE()) WHEN 1 THEN 1 ELSE 0 END 
		) CODE_FREQUENCY
		, CASE DATEPART(DW,GETDATE()) WHEN 1 THEN 1 ELSE 0 END SUNDAY
		, CASE DATEPART(DW,GETDATE()) WHEN 2 THEN 1 ELSE 0 END MONDAY
		, CASE DATEPART(DW,GETDATE()) WHEN 3 THEN 1 ELSE 0 END TUESDAY
		, CASE DATEPART(DW,GETDATE()) WHEN 4 THEN 1 ELSE 0 END WEDNESDAY
		, CASE DATEPART(DW,GETDATE()) WHEN 5 THEN 1 ELSE 0 END THURSDAY
		, CASE DATEPART(DW,GETDATE()) WHEN 6 THEN 1 ELSE 0 END FRIDCAY
		, CASE DATEPART(DW,GETDATE()) WHEN 7 THEN 1 ELSE 0 END SATURDAY
		, 1 FREQUENCY_WEEKS
		, CONVERT(DATE, DATEADD(day,
               -1 - (DATEPART(dw, GETDATE()) + @@DATEFIRST - 2) % 7,
               GETDATE()
       )) AS LAST_WEEK_VISITED
		, GETDATE() LAST_UPDATED
		, 'BULK_DATA' LAST_UPDATED_BY
		, [SELLER_CODE]
		, 'SALE' TYPE_TASK
		, 'BULK_DATA'REFERENCE_SOURCE
		,NULL
	FROM SWIFT_INTERFACES_ONLINE.diprocom.ERP_VIEW_SELLER

	INSERT INTO SWIFT_EXPRESS.diprocom.SWIFT_FREQUENCY_X_CUSTOMER 
	(
		[ID_FREQUENCY]
		,[CODE_CUSTOMER]
		,[PRIORITY]	
	)
	SELECT 
		[F].[ID_FREQUENCY]
		,[C].[CODE_CUSTOMER]
		,1 AS [PRIORITY]
	 FROM [SWIFT_INTERFACES_ONLINE].[diprocom].[ERP_VIEW_COSTUMER] C
		INNER JOIN SWIFT_EXPRESS.diprocom.SWIFT_FREQUENCY F ON C.[SELLER_DEFAULT_CODE] = F.CODE_ROUTE
		WHERE F.REFERENCE_SOURCE = 'BULK_DATA'


END