CREATE PROC [PACASA].[SWIFT_SP_UPDATE_PICKING_DETAIL_FF]
@PICKING_DETAIL INT,
@RESULT FLOAT
AS
UPDATE [PACASA].SWIFT_PICKING_DETAIL
	SET
		RESULT = @RESULT
	WHERE
		PICKING_DETAIL = @PICKING_DETAIL




